replicaCount: 1

image: morozovav82/product:1.0

service:
  type: NodePort
  port: 9000

appBasePath: '/product'

postgresql:
  fullname: users-postgresql
  postgresqlDatabase: users
  postgresqlUsername: users
  postgresqlPassword: qwerty123
  service:
    port: "5432"

mq:
  url: mq-rabbitmq.morozovav.svc.cluster.local
  port: 5672
  username: rabbit
  password: rabbit

ingress:
  enabled: true
  hosts:
    - host: arch.homework
      paths: ["/product"]
      
metrics:
  serviceMonitor:
    enabled: false