replicaCount: 1

image: morozovav82/product:2.0

service:
  type: NodePort
  port: 9000

appBasePath: '/product'
authSigninUrl: 'http://$host/auth/signin'
authAuthUrl: 'http://auth-auth-chart.morozovav.svc.cluster.local:9010/auth'
usersUrl: 'http://users-users-chart.morozovav.svc.cluster.local:9000'

postgresql:
  fullname: postgresql.morozovav.svc.cluster.local
  postgresqlDatabase: users
  postgresqlUsername: users
  postgresqlPassword: qwerty123
  service:
    port: "5432"

mq:
  url: mq-rabbitmq.morozovav.svc.cluster.local
  port: 5672
  username: rabbit
  password: rabbit

redis:
  host: redis-master.morozovav.svc.cluster.local
  port: 6379

ingress:
  enabled: true
  hosts:
    - host: arch.homework
      paths: ["/product"]
      
metrics:
  serviceMonitor:
    enabled: true