#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace

server:
  port: 8085
  servlet:
    context-path: '/product'

spring:
    datasource:
      driver-class-name: 'org.postgresql.Driver'
      url: jdbc:postgresql://localhost:5432/postgres?currentShema=product
      username: product
      password: qwerty123
    rabbitmq:
      host: localhost
      port: 5672
      username: rabbit
      password: rabbit

app.basePath: /product
